// Code generated by .tools/gen_ngap_samples.go; DO NOT EDIT.

package ngapTestpacket

import (
	"github.com/free5gc/ngap/aper"
	"github.com/free5gc/ngap/ie"
	ngapMessage "github.com/free5gc/ngap/message"
)

func sampleAMFStatusIndication() ngapMessage.Message {
	plmnIdentity := &ie.PLMNIdentity{Value: aper.OctetString([]byte{0x00, 0xF1, 0x53})}
	_ = plmnIdentity
	amfRegionId := &ie.AMFRegionID{Value: aper.BitString{Bytes: []byte{0xCA}, BitLength: 8}}
	_ = amfRegionId
	amfSetId := &ie.AMFSetID{Value: aper.BitString{Bytes: []byte{0xFE, 0x00}, BitLength: 10}}
	_ = amfSetId
	amfPointer := &ie.AMFPointer{Value: aper.BitString{Bytes: []byte{0x00}, BitLength: 6}}
	_ = amfPointer
	return &ngapMessage.AMFStatusIndication{
		UnavailableGUAMIList: &ie.UnavailableGUAMIList{
			List: []ie.UnavailableGUAMIItem{
				{
					GUAMI: &ie.GUAMI{
						PLMNIdentity: plmnIdentity,
						AMFRegionID:  amfRegionId,
						AMFSetID:     amfSetId,
						AMFPointer:   amfPointer,
					},
				},
			},
		},
	}
}

func sampleErrorIndication() ngapMessage.Message {
	return &ngapMessage.ErrorIndication{
		Cause: &ie.Cause{
			Choice: &ie.CauseRadioNetwork{
				Value: ie.CauseRadioNetworkPresentUnknownLocalUENGAPID,
			},
		},
	}
}

func sampleHandoverCancel() ngapMessage.Message {
	return &ngapMessage.HandoverCancel{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 776276781756,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		Cause: &ie.Cause{
			Choice: &ie.CauseRadioNetwork{
				Value: ie.CauseRadioNetworkPresentHandoverCancelled,
			},
		},
	}
}

func sampleHandoverFailure() ngapMessage.Message {
	return &ngapMessage.HandoverFailure{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 1009452830939,
		},
		Cause: &ie.Cause{
			Choice: &ie.CauseRadioNetwork{
				Value: ie.CauseRadioNetworkPresentHoFailureInTarget5GCNgranNodeOrTargetSystem,
			},
		},
	}
}

func sampleHandoverNotify() ngapMessage.Message {
	plmnIdentity_case1 := &ie.PLMNIdentity{Value: aper.OctetString([]byte{0x13, 0x30, 0x01})}
	_ = plmnIdentity_case1
	tac_case1 := &ie.TAC{Value: aper.OctetString([]byte{0x00, 0x00, 0x01})}
	_ = tac_case1
	nrCellIdentity := &ie.NRCellIdentity{
		Value: aper.BitString{
			Bytes:     []byte{0x00, 0x00, 0x0d, 0x90, 0x30},
			BitLength: 36,
		},
	}
	_ = nrCellIdentity
	return &ngapMessage.HandoverNotify{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 887252622092,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		UserLocationInformation: &ie.UserLocationInformation{
			Choice: &ie.UserLocationInformationNR{
				NRCGI: &ie.NRCGI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString{0x02, 0xf8, 0x39},
					},
					NRCellIdentity: &ie.NRCellIdentity{
						Value: aper.BitString{
							Bytes:     []byte{0x00, 0x01, 0x02, 0x00, 0x10},
							BitLength: 36,
						},
					},
					IEExtensions: nil,
				},
				TAI: &ie.TAI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString{0x02, 0xf8, 0x39},
					},
					TAC: &ie.TAC{
						Value: aper.OctetString{0x00, 0x00, 0x01},
					},
					IEExtensions: nil,
				},
				TimeStamp:    nil,
				IEExtensions: nil,
			},
		},
		NotifySourceNGRANNode: nil,
	}
}

func sampleHandoverRequestAcknowledge() ngapMessage.Message {
	ipv4Addr := &ie.TransportLayerAddress{
		Value: aper.BitString{
			Bytes:     []byte{0xac, 0x10, 0x03, 0x02},
			BitLength: 32,
		},
	}
	_ = ipv4Addr
	gtpteid := &ie.GTPTEID{Value: aper.OctetString([]byte{0x00, 0x00, 0x00, 0x01})}
	_ = gtpteid
	handoverRequestAcknowledgeTransfer := ie.HandoverRequestAcknowledgeTransfer{
		DLNGUUPTNLInformation: &ie.UPTransportLayerInformation{
			Choice: &ie.GTPTunnel{
				TransportLayerAddress: ipv4Addr,
				GTPTEID:               gtpteid,
			},
		},
		DLForwardingUPTNLInformation: &ie.UPTransportLayerInformation{
			Choice: &ie.GTPTunnel{
				TransportLayerAddress: ipv4Addr,
				GTPTEID:               gtpteid,
			},
		},
		QosFlowSetupResponseList: &ie.QosFlowListWithDataForwarding{
			List: []ie.QosFlowItemWithDataForwarding{
				{
					QosFlowIdentifier: &ie.QosFlowIdentifier{
						Value: 9,
					},
				},
			},
		},
	}
	_ = handoverRequestAcknowledgeTransfer
	handoverRequestAcknowledgeTransferBytes, err := ie.MarshalBinary(&handoverRequestAcknowledgeTransfer)
	_ = handoverRequestAcknowledgeTransferBytes
	_ = err
	handoverRequestAcknowledgeTransferOS := aper.OctetString(handoverRequestAcknowledgeTransferBytes)
	_ = handoverRequestAcknowledgeTransferOS
	targetToSourceTransparentContainer := &ie.TargetToSourceTransparentContainer{
		Value: aper.OctetString([]byte{0x00, 0x04, 0x74, 0x65, 0x73, 0x74}),
	}
	_ = targetToSourceTransparentContainer
	return &ngapMessage.HandoverRequestAcknowledge{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 887252622092,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		PDUSessionResourceAdmittedList: &ie.PDUSessionResourceAdmittedList{
			List: []ie.PDUSessionResourceAdmittedItem{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 10,
					},
					HandoverRequestAcknowledgeTransfer: &aper.OctetString{
						0x40, 0x07, 0xc0, 0xac, 0x10, 0x1f, 0x33, 0x00, 0x00, 0x00, 0x01, 0x01, 0xf0,
						0xac, 0x10, 0x1f, 0x33, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01,
					},
					IEExtensions: nil,
				},
			},
		},
		PDUSessionResourceFailedToSetupListHOAck: nil,

		TargetToSourceTransparentContainer: &ie.TargetToSourceTransparentContainer{
			Value: aper.OctetString{
				0x00, 0x81, 0x82, 0x08, 0x17, 0xf5, 0x55, 0x28,
				0x22, 0x02, 0x93, 0x78, 0xfc, 0x0a, 0x06, 0x01,
				0x80, 0x3e, 0x80, 0x40, 0xf2, 0x80, 0x2a, 0x76,
				0x80, 0xa0, 0x49, 0x58, 0x0f, 0xff, 0xff, 0xff,
				0x38, 0xf7, 0xbc, 0x06, 0x02, 0x84, 0xe0, 0x02,
				0x20, 0x60, 0x22, 0x05, 0xa0, 0x5c, 0xde, 0x04,
				0x24, 0x44, 0xaa, 0x0b, 0x9b, 0xc0, 0x02, 0x20,
				0x60, 0x82, 0x08, 0x60, 0x85, 0x40, 0x02, 0x42,
				0x05, 0x09, 0x70, 0x11, 0x40, 0x83, 0x0f, 0x42,
				0x02, 0x85, 0x06, 0x3e, 0x84, 0x05, 0x1a, 0x0c,
				0x45, 0x08, 0x0f, 0x84, 0x56, 0x01, 0xa0, 0xf5,
				0xa8, 0x04, 0x1f, 0xc9, 0x6e, 0xe3, 0xf7, 0x5a,
				0x54, 0xed, 0x00, 0x13, 0x8a, 0x9a, 0x10, 0x10,
				0x00, 0x31, 0x00, 0x10, 0x2a, 0x69, 0x06, 0x04,
				0x4b, 0x35, 0x8a, 0x81, 0xb8, 0x20, 0x10, 0x00,
				0x00, 0x88, 0x40, 0x0d, 0x28, 0x05, 0x10, 0x15,
				0xa0, 0x2f, 0xe1, 0x00, 0x00, 0x18, 0x87, 0xee,
				0x04, 0x4b, 0x36, 0x24, 0xe8, 0x0a, 0xc6, 0x86,
				0x69, 0xac, 0x64, 0x00, 0x93, 0x9c, 0x51, 0xb8,
				0x43, 0x70, 0xc6, 0xe2, 0x0d, 0x98, 0x4a, 0x89,
				0x1d, 0xd6, 0x02, 0x8a, 0x54, 0x07, 0x60, 0x12,
				0x50, 0x15, 0x80, 0x89, 0xea, 0x71, 0x01, 0x26,
				0x9d, 0x01, 0x58, 0xd0, 0xcd, 0x60, 0x00, 0x10,
				0x04, 0x93, 0x03, 0x2a, 0x00, 0x02, 0x00, 0x01,
				0xff, 0xff, 0xfe, 0x02, 0x0d, 0xc2, 0x10, 0x80,
				0x00, 0x0c, 0x05, 0xb0, 0x82, 0x83, 0xee, 0xc8,
				0x2c, 0xe0, 0x14, 0x40, 0x60, 0x80, 0xc7, 0x00,
				0xd4, 0x60, 0x40, 0x45, 0x52, 0x80, 0x1b, 0x86,
				0xf0, 0x00, 0x02, 0x46, 0xaa, 0x49, 0xb0, 0x38,
				0x00, 0x20, 0x81, 0x84, 0x0a, 0x18, 0x3d, 0x00,
				0x91, 0x44, 0x01, 0x42, 0x80, 0x00, 0x00, 0x0d,
				0x00, 0x80, 0x40, 0x34, 0x04, 0x02, 0x00, 0xd0,
				0x18, 0x0c, 0x03, 0x40, 0x80, 0x40, 0x0d, 0x02,
				0x81, 0x40, 0x34, 0x0c, 0x06, 0x00, 0xd0, 0x38,
				0x1c, 0x03, 0x41, 0x00, 0x90, 0x0d, 0x04, 0x82,
				0x10, 0x70, 0x14, 0x0d, 0x41, 0xc9, 0x38, 0x60,
				0x39, 0x88, 0xe4, 0x68, 0xac, 0xf5, 0x60, 0x00,
				0x00, 0x7e, 0x42, 0x10, 0x84, 0x00, 0x85, 0xd2,
				0x18, 0xf7, 0x52, 0x48, 0x75, 0x06, 0x50, 0x30,
				0x42, 0x03, 0x18, 0x43, 0x70, 0xc6, 0xe2, 0x50,
				0x3c, 0x00, 0x00, 0x41, 0x23, 0x28, 0x00, 0x08,
				0x00, 0x00, 0x00, 0x00, 0x05, 0x80, 0x00, 0x01,
				0x95, 0x03, 0x00, 0xc4, 0x55, 0x45, 0x00, 0x06,
				0x00, 0x30, 0x4d, 0x28, 0x01, 0xb8, 0x03, 0xdd,
				0x33, 0x01, 0x00, 0x00, 0x02, 0x07, 0x04, 0xa0,
				0x03, 0x70, 0xdc, 0x00, 0x00, 0x00, 0x40, 0x10,
				0x00, 0x20, 0x18, 0x00, 0x20, 0x0b, 0x40, 0x00,
				0x02, 0x40, 0x18, 0x05, 0x4a, 0x77, 0xff, 0xff,
				0x1f, 0x81, 0xa4, 0x00, 0x20,
			},
		},
		CriticalityDiagnostics: nil,
		NPNAccessInformation:   nil,
		RedCapIndication:       nil,
	}
}

func sampleHandoverRequired() ngapMessage.Message {
	plmnIdentity_case1 := &ie.PLMNIdentity{Value: aper.OctetString([]byte{0x13, 0x30, 0x01})}
	_ = plmnIdentity_case1
	tac_case1 := &ie.TAC{Value: aper.OctetString([]byte{0x00, 0x00, 0x01})}
	_ = tac_case1
	handoverRequiredTransfer := ie.HandoverRequiredTransfer{
		DirectForwardingPathAvailability: &ie.DirectForwardingPathAvailability{
			Value: ie.DirectForwardingPathAvailabilityPresentDirectPathAvailable,
		},
	}
	_ = handoverRequiredTransfer
	handoverRequiredTransferBytes, err := ie.MarshalBinary(&handoverRequiredTransfer)
	_ = handoverRequiredTransferBytes
	_ = err
	handoverRequiredTransferOS := aper.OctetString(handoverRequiredTransferBytes)
	_ = handoverRequiredTransferOS
	targetCellNrCellIdentity := &ie.NRCellIdentity{
		Value: aper.BitString{
			Bytes:     []byte{0x00, 0x00, 0x0d, 0x90, 0x30},
			BitLength: 36,
		},
	}
	_ = targetCellNrCellIdentity
	targetCellGnbId := &ie.GNBID{
		Choice: &ie.GNBIDForGNBID{
			Value: aper.BitString{
				Bytes:     []byte{0x00, 0x00, 0x0d, 0x90},
				BitLength: 32,
			},
		},
	}
	_ = targetCellGnbId
	lastVisitedCellNrCellIdentity := &ie.NRCellIdentity{
		Value: aper.BitString{
			Bytes:     []byte{0x00, 0x00, 0x02, 0xb6, 0x70},
			BitLength: 36,
		},
	}
	_ = lastVisitedCellNrCellIdentity
	sourceNGRANNodeToTargetNGRANNodeTransparentContainer := ie.SourceNGRANNodeToTargetNGRANNodeTransparentContainer{
		RRCContainer: &ie.RRCContainer{
			Value: aper.OctetString([]byte{
				0x10, 0x00, 0x09,
				0x33, 0x31, 0x30, 0x33, 0x31, 0x30, 0x31, 0x34, 0x30, 0x30, 0x30, 0x30,
				0x31, 0x32, 0x30,
			}),
		},
		PDUSessionResourceInformationList: &ie.PDUSessionResourceInformationList{
			List: []ie.PDUSessionResourceInformationItem{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 5,
					},
					QosFlowInformationList: &ie.QosFlowInformationList{
						List: []ie.QosFlowInformationItem{
							{
								QosFlowIdentifier: &ie.QosFlowIdentifier{
									Value: 9,
								},
							},
						},
					},
				},
			},
		},
		TargetCellID: &ie.NGRANCGI{
			Choice: &ie.NRCGI{
				PLMNIdentity:   plmnIdentity_case1,
				NRCellIdentity: targetCellNrCellIdentity,
			},
		},
		UEHistoryInformation: &ie.UEHistoryInformation{
			List: []ie.LastVisitedCellItem{
				{
					LastVisitedCellInformation: &ie.LastVisitedCellInformation{
						Choice: &ie.LastVisitedNGRANCellInformation{
							GlobalCellID: &ie.NGRANCGI{
								Choice: &ie.NRCGI{
									PLMNIdentity:   plmnIdentity_case1,
									NRCellIdentity: lastVisitedCellNrCellIdentity,
								},
							},
							CellType: &ie.CellType{
								CellSize: &ie.CellSize{
									Value: ie.CellSizePresentMedium,
								},
							},
							TimeUEStayedInCell: &ie.TimeUEStayedInCell{
								Value: 100,
							},
						},
					},
				},
			},
		},
	}
	_ = sourceNGRANNodeToTargetNGRANNodeTransparentContainer
	sourceNGRANNodeToTargetNGRANNodeTransparentContainerBytes, err := ie.MarshalBinary(
		&sourceNGRANNodeToTargetNGRANNodeTransparentContainer,
	)
	_ = sourceNGRANNodeToTargetNGRANNodeTransparentContainerBytes
	_ = err
	sourceNGRANNodeToTargetNGRANNodeTransparentContainerOS := aper.OctetString(
		sourceNGRANNodeToTargetNGRANNodeTransparentContainerBytes)
	_ = sourceNGRANNodeToTargetNGRANNodeTransparentContainerOS
	return &ngapMessage.HandoverRequired{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 910057611806,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		HandoverType: &ie.HandoverType{
			Value: 0,
		},
		Cause: &ie.Cause{
			Choice: &ie.CauseRadioNetwork{
				Value: ie.CauseRadioNetworkPresentHandoverDesirableForRadioReason,
			},
		},
		TargetID: &ie.TargetID{
			Choice: &ie.TargetRANNodeID{
				GlobalRANNodeID: &ie.GlobalRANNodeID{
					Choice: &ie.GlobalGNBID{
						PLMNIdentity: &ie.PLMNIdentity{
							Value: []byte{0x02, 0xf8, 0x39},
						},
						GNBID: &ie.GNBID{
							Choice: &ie.GNBIDForGNBID{
								Value: aper.BitString{
									Bytes:     []uint8{0x00, 0x01, 0x02},
									BitLength: 24,
								},
							},
						},
						IEExtensions: nil,
					},
				},
				SelectedTAI: &ie.TAI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: []byte{0x02, 0xf8, 0x39},
					},
					TAC: &ie.TAC{
						Value: []byte{0x30, 0x33, 0x99},
					},
					IEExtensions: nil,
				},
				IEExtensions: nil,
			},
		},
		DirectForwardingPathAvailability: nil,
		PDUSessionResourceListHORqd: &ie.PDUSessionResourceListHORqd{
			List: []ie.PDUSessionResourceItemHORqd{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 10,
					},
					HandoverRequiredTransfer: &aper.OctetString{0x40},
					IEExtensions:             nil,
				},
			},
		},
		SourceToTargetTransparentContainer: &ie.SourceToTargetTransparentContainer{
			Value: []byte{
				0x40, 0x03, 0x00, 0x00, 0x11, 0x00, 0x00, 0x01,
				0x00, 0x01, 0x00, 0x02, 0xf8, 0x39, 0x00, 0x01,
				0x02, 0x00, 0x10, 0x00, 0x00, 0x02, 0xf8, 0x39,
				0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x0a,
			},
		},
	}
}

func sampleInitialContextSetupFailure() ngapMessage.Message {
	pDUSessionResourceSetupUnsuccessfulTransfer := ie.PDUSessionResourceSetupUnsuccessfulTransfer{
		Cause: &ie.Cause{
			Choice: &ie.CauseRadioNetwork{
				Value: ie.CauseRadioNetworkPresentFailureInRadioInterfaceProcedure,
			},
		},
	}
	_ = pDUSessionResourceSetupUnsuccessfulTransfer
	pDUSessionResourceSetupUnsuccessfulTransferBytes, err := ie.MarshalBinary(&pDUSessionResourceSetupUnsuccessfulTransfer)
	_ = pDUSessionResourceSetupUnsuccessfulTransferBytes
	_ = err
	pDUSessionResourceSetupUnsuccessfulTransferOS := aper.OctetString(pDUSessionResourceSetupUnsuccessfulTransferBytes)
	_ = pDUSessionResourceSetupUnsuccessfulTransferOS
	return &ngapMessage.InitialContextSetupFailure{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 4,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 142,
		},
		PDUSessionResourceFailedToSetupListCxtFail: &ie.PDUSessionResourceFailedToSetupListCxtFail{
			List: []ie.PDUSessionResourceFailedToSetupItemCxtFail{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 1,
					},
					PDUSessionResourceSetupUnsuccessfulTransfer: &pDUSessionResourceSetupUnsuccessfulTransferOS,
				},
			},
		},
		Cause: &ie.Cause{
			Choice: &ie.CauseRadioNetwork{
				Value: ie.CauseRadioNetworkPresentFailureInRadioInterfaceProcedure,
			},
		},
	}
}

func sampleInitialContextSetupResponse() ngapMessage.Message {
	ipv4Addr := &ie.TransportLayerAddress{
		Value: aper.BitString{
			Bytes:     []byte{0xac, 0x10, 0x03, 0x01},
			BitLength: 32,
		},
	}
	_ = ipv4Addr
	gtpteid := &ie.GTPTEID{
		Value: aper.OctetString([]byte{0x00, 0x00, 0x00, 0x01}),
	}
	_ = gtpteid
	pDUSessionResourceSetupResponseTransfer := ie.PDUSessionResourceSetupResponseTransfer{
		DLQosFlowPerTNLInformation: &ie.QosFlowPerTNLInformation{
			UPTransportLayerInformation: &ie.UPTransportLayerInformation{
				Choice: &ie.GTPTunnel{
					TransportLayerAddress: ipv4Addr,
					GTPTEID:               gtpteid,
				},
			},
			AssociatedQosFlowList: &ie.AssociatedQosFlowList{
				List: []ie.AssociatedQosFlowItem{
					{
						QosFlowIdentifier: &ie.QosFlowIdentifier{
							Value: 9,
						},
					},
				},
			},
		},
	}
	_ = pDUSessionResourceSetupResponseTransfer
	marshalledPduSessionResourceSetupResponseTransfer, err := ie.MarshalBinary(
		&pDUSessionResourceSetupResponseTransfer)
	_ = marshalledPduSessionResourceSetupResponseTransfer
	_ = err
	marshalledPduSessionResourceSetupResponseTransferOS := aper.OctetString(
		marshalledPduSessionResourceSetupResponseTransfer)
	_ = marshalledPduSessionResourceSetupResponseTransferOS
	return &ngapMessage.InitialContextSetupResponse{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 1,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 3456106496,
		},
		PDUSessionResourceSetupListCxtRes: &ie.PDUSessionResourceSetupListCxtRes{
			List: []ie.PDUSessionResourceSetupItemCxtRes{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 5,
					},
					PDUSessionResourceSetupResponseTransfer: &marshalledPduSessionResourceSetupResponseTransferOS,
				},
			},
		},
	}
}

func sampleInitialUEMessage() ngapMessage.Message {
	return &ngapMessage.InitialUEMessage{
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		NASPDU: &ie.NASPDU{
			Value: aper.OctetString([]byte{
				0x7e, 0x00, 0x41, 0x79, 0x00, 0x0c, 0x01, 0x02,
				0xf8, 0x39, 0xf0, 0xff, 0x00, 0x00, 0x00, 0x00,
				0x47, 0x78, 0x2e, 0x02, 0xe0, 0xe0,
			}),
		},
		UserLocationInformation: &ie.UserLocationInformation{
			Choice: &ie.UserLocationInformationNR{
				NRCGI: &ie.NRCGI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString([]byte{0x02, 0xf8, 0x39}),
					},
					NRCellIdentity: &ie.NRCellIdentity{
						Value: aper.BitString{
							Bytes:     []byte{0x00, 0x00, 0x04, 0x00, 0x10},
							BitLength: 36,
						},
					},
					IEExtensions: nil,
				},
				TAI: &ie.TAI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString([]byte{0x02, 0xf8, 0x39}),
					},
					TAC: &ie.TAC{
						Value: aper.OctetString([]byte{0x00, 0x00, 0x01}),
					},
					IEExtensions: nil,
				},
				TimeStamp: nil,
				IEExtensions: &ie.ProtocolExtensionContainerUserLocationInformationNRExtIEs{
					List: []ie.UserLocationInformationNRExtIEs{
						{
							Id: &ie.ProtocolExtensionID{
								Value: 263,
							},
							Criticality: &ie.Criticality{
								Value: aper.Enumerated(0),
							},
							PSCellInformation: nil,
							NID: &ie.NID{
								Value: aper.BitString{
									Bytes:     []byte{0x10, 0x00, 0x00, 0x00, 0x00, 0x10},
									BitLength: 44,
								},
							},
							NRNTNTAIInformation: nil,
						},
					},
				},
			},
		},
		RRCEstablishmentCause: &ie.RRCEstablishmentCause{
			Value: aper.Enumerated(3),
		},
		FiveGSTMSI:                          nil,
		AMFSetID:                            nil,
		UEContextRequest:                    &ie.UEContextRequest{Value: aper.Enumerated(0)},
		AllowedNSSAI:                        nil,
		SourceToTargetAMFInformationReroute: nil,
		SelectedPLMNIdentity:                nil,
		IABNodeIndication:                   nil,
		CEmodeBSupportIndicator:             nil,
		LTEMIndication:                      nil,
		EDTSession:                          nil,
		AuthenticatedIndication:             nil,
		NPNAccessInformation:                nil,
		RedCapIndication:                    nil,
	}
}

func sampleNGReset() ngapMessage.Message {
	return &ngapMessage.NGReset{
		Cause: &ie.Cause{
			Choice: &ie.CauseRadioNetwork{
				Value: ie.CauseRadioNetworkPresentReleaseDueToNgranGeneratedReason,
			},
		},
		ResetType: &ie.ResetType{
			Choice: &ie.UEAssociatedLogicalNGConnectionList{
				List: []ie.UEAssociatedLogicalNGConnectionItem{
					{
						RANUENGAPID: &ie.RANUENGAPID{
							Value: 94,
						},
					},
					{
						RANUENGAPID: &ie.RANUENGAPID{
							Value: 95,
						},
					},
					{
						RANUENGAPID: &ie.RANUENGAPID{
							Value: 296,
						},
					},
				},
			},
		},
	}
}

func sampleNGResetAcknowledge() ngapMessage.Message {
	return &ngapMessage.NGResetAcknowledge{
		UEAssociatedLogicalNGConnectionList: &ie.UEAssociatedLogicalNGConnectionList{
			List: []ie.UEAssociatedLogicalNGConnectionItem{
				{
					RANUENGAPID: &ie.RANUENGAPID{
						Value: 94,
					},
				},
				{
					RANUENGAPID: &ie.RANUENGAPID{
						Value: 95,
					},
				},
				{
					RANUENGAPID: &ie.RANUENGAPID{
						Value: 296,
					},
				},
			},
		},
	}
}

func sampleNGSetupRequest() ngapMessage.Message {
	return &ngapMessage.NGSetupRequest{
		GlobalRANNodeID: &ie.GlobalRANNodeID{
			Choice: &ie.GlobalGNBID{
				PLMNIdentity: &ie.PLMNIdentity{
					Value: aper.OctetString{
						0x02, 0xf8, 0x39,
					},
				},
				GNBID: &ie.GNBID{
					Choice: &ie.GNBIDForGNBID{
						Value: aper.BitString{
							Bytes:     []byte{0x00, 0x00, 0x04},
							BitLength: 22,
						},
					},
				},
				IEExtensions: nil,
			},
		},
		RANNodeName: &ie.RANNodeName{
			Value: aper.PrintableString("free5gc-1"),
		},
		SupportedTAList: &ie.SupportedTAList{
			List: []ie.SupportedTAItem{
				{
					TAC: &ie.TAC{
						Value: aper.OctetString{
							0x00, 0x00, 0x01,
						},
					},
					BroadcastPLMNList: &ie.BroadcastPLMNList{
						List: []ie.BroadcastPLMNItem{
							{
								PLMNIdentity: &ie.PLMNIdentity{
									Value: aper.OctetString{
										0x02, 0xf8, 0x39,
									},
								},
								TAISliceSupportList: &ie.SliceSupportList{
									List: []ie.SliceSupportItem{
										{
											SNSSAI: &ie.SNSSAI{
												SST: &ie.SST{
													Value: aper.OctetString{
														0x01,
													},
												},
												SD: &ie.SD{
													Value: aper.OctetString{
														0x11, 0x22, 0x33,
													},
												},
												IEExtensions: nil,
											},
											IEExtensions: nil,
										},
									},
								},
								IEExtensions: &ie.ProtocolExtensionContainerBroadcastPLMNItemExtIEs{
									List: []ie.BroadcastPLMNItemExtIEs{
										{
											Id: &ie.ProtocolExtensionID{
												Value: int64(258),
											},
											Criticality: &ie.Criticality{
												Value: aper.Enumerated(0),
											},
											NPNSupport: &ie.NPNSupport{
												Choice: &ie.NID{
													Value: aper.BitString{
														Bytes: []byte{
															0x10, 0x00, 0x00, 0x00, 0x00, 0x10,
														},
														BitLength: 44,
													},
												},
											},
											ExtendedTAISliceSupportList: nil,
											TAINSAGSupportList:          nil,
										},
									},
								},
							},
						},
					},
					IEExtensions: nil,
				},
			},
		},
		DefaultPagingDRX: &ie.PagingDRX{
			Value: aper.Enumerated(2),
		},
		UERetentionInformation: nil,
		NBIoTDefaultPagingDRX:  nil,
		ExtendedRANNodeName:    nil,
	}
}

func sampleNGSetupResponse() ngapMessage.Message {
	return &ngapMessage.NGSetupResponse{
		AMFName: &ie.AMFName{
			Value: aper.PrintableString("amf1"),
		},
		ServedGUAMIList: &ie.ServedGUAMIList{
			List: []ie.ServedGUAMIItem{
				{
					GUAMI: &ie.GUAMI{
						PLMNIdentity: &ie.PLMNIdentity{
							Value: aper.OctetString([]byte{0x02, 0xf8, 0x39}),
						},
						AMFRegionID: &ie.AMFRegionID{
							Value: aper.BitString{
								Bytes:     []byte{0x01},
								BitLength: 8,
							},
						},
						AMFSetID: &ie.AMFSetID{
							Value: aper.BitString{
								Bytes:     []byte{0x00, 0x40},
								BitLength: 10,
							},
						},
						AMFPointer: &ie.AMFPointer{
							Value: aper.BitString{
								Bytes:     []byte{0x04},
								BitLength: 6,
							},
						},
						IEExtensions: nil,
					},
					BackupAMFName: nil,
					IEExtensions:  nil,
				},
			},
		},
		RelativeAMFCapacity: &ie.RelativeAMFCapacity{
			Value: 255,
		},
		PLMNSupportList: &ie.PLMNSupportList{
			List: []ie.PLMNSupportItem{
				{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString([]byte{0x02, 0xf8, 0x39}),
					},
					SliceSupportList: &ie.SliceSupportList{
						List: []ie.SliceSupportItem{
							{
								SNSSAI: &ie.SNSSAI{
									SST: &ie.SST{
										Value: aper.OctetString([]byte{0x01}),
									},
									SD: &ie.SD{
										Value: aper.OctetString([]byte{0x01, 0x02, 0x03}),
									},
									IEExtensions: nil,
								},
								IEExtensions: nil,
							},
						},
					},
					IEExtensions: &ie.ProtocolExtensionContainerPLMNSupportItemExtIEs{
						List: []ie.PLMNSupportItemExtIEs{
							{
								Id: &ie.ProtocolExtensionID{
									Value: 258,
								},
								Criticality: &ie.Criticality{
									Value: aper.Enumerated(0),
								},
								NPNSupport: &ie.NPNSupport{
									Choice: &ie.NID{
										Value: aper.BitString{
											Bytes:     []byte{0x10, 0x00, 0x00, 0x00, 0x00, 0x10},
											BitLength: 44,
										},
									},
								},
								ExtendedSliceSupportList: nil,
								OnboardingSupport:        nil,
							},
						},
					},
				},
			},
		},
		CriticalityDiagnostics: nil,
		UERetentionInformation: nil,
		IABSupported:           nil,
		ExtendedAMFName:        nil,
	}
}

func samplePDUSessionResourceModifyResponse() ngapMessage.Message {
	return &ngapMessage.PDUSessionResourceModifyResponse{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 665250635458,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		PDUSessionResourceModifyListModRes: &ie.PDUSessionResourceModifyListModRes{
			List: []ie.PDUSessionResourceModifyItemModRes{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 10,
					},

					PDUSessionResourceModifyResponseTransfer: &aper.OctetString{0x10, 0x00, 0x08},
				},
			},
		},
		UserLocationInformation: &ie.UserLocationInformation{
			Choice: &ie.UserLocationInformationNR{
				NRCGI: &ie.NRCGI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString{0x02, 0xf8, 0x39},
					},
					NRCellIdentity: &ie.NRCellIdentity{
						Value: aper.BitString{
							Bytes:     []byte{0x00, 0x00, 0x00, 0x00, 0x20},
							BitLength: 36,
						},
					},
				},
				TAI: &ie.TAI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString{0x02, 0xf8, 0x39},
					},
					TAC: &ie.TAC{
						Value: aper.OctetString{0x00, 0x00, 0x11},
					},
				},
			},
		},
	}
}

func samplePDUSessionResourceReleaseCommand() ngapMessage.Message {
	pDUSessionResourceReleaseCommandTransfer := ie.PDUSessionResourceReleaseCommandTransfer{
		Cause: &ie.Cause{
			Choice: &ie.CauseNas{
				Value: ie.CauseNasPresentNormalRelease,
			},
		},
	}
	_ = pDUSessionResourceReleaseCommandTransfer
	pDUSessionResourceReleaseCommandTransferBytes, err := ie.MarshalBinary(&pDUSessionResourceReleaseCommandTransfer)
	_ = pDUSessionResourceReleaseCommandTransferBytes
	_ = err
	pDUSessionResourceReleaseCommandTransferOS := aper.OctetString(
		pDUSessionResourceReleaseCommandTransferBytes)
	_ = pDUSessionResourceReleaseCommandTransferOS
	return &ngapMessage.PDUSessionResourceReleaseCommand{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 966541003059,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		NASPDU: &ie.NASPDU{
			Value: aper.OctetString{0x7e, 0x02, 0x6c, 0xed, 0xba, 0x34, 0x04, 0x7e, 0x00, 0x68, 0x01, 0x00, 0x05, 0x2e, 0x0a, 0x00, 0xd3, 0x24, 0x12, 0x0a},
		},
		PDUSessionResourceToReleaseListRelCmd: &ie.PDUSessionResourceToReleaseListRelCmd{
			List: []ie.PDUSessionResourceToReleaseItemRelCmd{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 10,
					},

					PDUSessionResourceReleaseCommandTransfer: &aper.OctetString{0x10},
				},
			},
		},
	}
}

func samplePDUSessionResourceReleaseResponse() ngapMessage.Message {
	PDUSessionResourceReleaseResponseTransferOS := aper.OctetString{0x00}
	_ = PDUSessionResourceReleaseResponseTransferOS
	return &ngapMessage.PDUSessionResourceReleaseResponse{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 966541003059,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		PDUSessionResourceReleasedListRelRes: &ie.PDUSessionResourceReleasedListRelRes{
			List: []ie.PDUSessionResourceReleasedItemRelRes{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 10,
					},

					PDUSessionResourceReleaseResponseTransfer: &aper.OctetString{0x00},
				},
			},
		},
	}
}

func samplePDUSessionResourceSetupResponse() ngapMessage.Message {
	ipv4Addr := &ie.TransportLayerAddress{
		Value: aper.BitString{
			Bytes:     []byte{0xac, 0x10, 0x03, 0x01},
			BitLength: 32,
		},
	}
	_ = ipv4Addr
	gtpteid := &ie.GTPTEID{Value: aper.OctetString([]byte{0x00, 0x00, 0x00, 0x01})}
	_ = gtpteid
	pDUSessionResourceSetupResponseTransfer := ie.PDUSessionResourceSetupResponseTransfer{
		DLQosFlowPerTNLInformation: &ie.QosFlowPerTNLInformation{
			UPTransportLayerInformation: &ie.UPTransportLayerInformation{
				Choice: &ie.GTPTunnel{
					TransportLayerAddress: ipv4Addr,
					GTPTEID:               gtpteid,
				},
			},
			AssociatedQosFlowList: &ie.AssociatedQosFlowList{
				List: []ie.AssociatedQosFlowItem{
					{
						QosFlowIdentifier: &ie.QosFlowIdentifier{
							Value: 9,
						},
					},
				},
			},
		},
	}
	_ = pDUSessionResourceSetupResponseTransfer
	marshalledPduSessionResourceSetupResponseTransferBytes, err := ie.MarshalBinary(&pDUSessionResourceSetupResponseTransfer)
	_ = marshalledPduSessionResourceSetupResponseTransferBytes
	_ = err
	marshalledPduSessionResourceSetupResponseTransferOS := aper.OctetString(
		marshalledPduSessionResourceSetupResponseTransferBytes)
	_ = marshalledPduSessionResourceSetupResponseTransferOS
	return &ngapMessage.PDUSessionResourceSetupResponse{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 1015608786343,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		PDUSessionResourceSetupListSURes: &ie.PDUSessionResourceSetupListSURes{
			List: []ie.PDUSessionResourceSetupItemSURes{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 10,
					},

					PDUSessionResourceSetupResponseTransfer: &aper.OctetString{
						0x00, 0x03, 0xe0, 0xac, 0x10, 0x1f, 0x32, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01,
					},
					IEExtensions: nil,
				},
			},
		},
	}
}

func samplePathSwitchRequest() ngapMessage.Message {
	plmnIdentity_case1 := &ie.PLMNIdentity{Value: aper.OctetString([]byte{0x13, 0x30, 0x01})}
	_ = plmnIdentity_case1
	tac_case1 := &ie.TAC{Value: aper.OctetString([]byte{0x00, 0x00, 0x01})}
	_ = tac_case1
	gtpTeid := &ie.GTPTEID{Value: aper.OctetString([]byte{0x00, 0x00, 0x00, 0x01})}
	_ = gtpTeid
	nrCellIdentity := &ie.NRCellIdentity{
		Value: aper.BitString{
			Bytes:     []byte{0x80, 0x00, 0x00, 0x00, 0x10},
			BitLength: 36,
		},
	}
	_ = nrCellIdentity
	nrEncryptAlgo := &ie.NRencryptionAlgorithms{
		Value: aper.BitString{
			Bytes:     []byte{0x00, 0x00},
			BitLength: 16,
		},
	}
	_ = nrEncryptAlgo
	nrIntegrityAlgo := &ie.NRintegrityProtectionAlgorithms{
		Value: aper.BitString{
			Bytes:     []byte{0x40, 0x00},
			BitLength: 16,
		},
	}
	_ = nrIntegrityAlgo
	eutraEncryptAlgo := &ie.EUTRAencryptionAlgorithms{
		Value: aper.BitString{
			Bytes:     []byte{0x00, 0x00},
			BitLength: 16,
		},
	}
	_ = eutraEncryptAlgo
	eutraIntegrityAlgo := &ie.EUTRAintegrityProtectionAlgorithms{
		Value: aper.BitString{
			Bytes:     []byte{0x00, 0x00},
			BitLength: 16,
		},
	}
	_ = eutraIntegrityAlgo
	ipv4Addr := &ie.TransportLayerAddress{
		Value: aper.BitString{
			Bytes:     []byte{0xac, 0x10, 0x03, 0x02},
			BitLength: 32,
		},
	}
	_ = ipv4Addr
	pathSwitchRequestTransfer := ie.PathSwitchRequestTransfer{
		DLNGUUPTNLInformation: &ie.UPTransportLayerInformation{
			Choice: &ie.GTPTunnel{
				TransportLayerAddress: ipv4Addr,
				GTPTEID:               gtpTeid,
			},
		},
		QosFlowAcceptedList: &ie.QosFlowAcceptedList{
			List: []ie.QosFlowAcceptedItem{
				{
					QosFlowIdentifier: &ie.QosFlowIdentifier{
						Value: 9,
					},
				},
			},
		},
	}
	_ = pathSwitchRequestTransfer
	pathSwitchRequestTransferBytes, err := ie.MarshalBinary(
		&pathSwitchRequestTransfer)
	_ = pathSwitchRequestTransferBytes
	_ = err
	pathSwitchRequestTransferOS := aper.OctetString(
		pathSwitchRequestTransferBytes)
	_ = pathSwitchRequestTransferOS
	return &ngapMessage.PathSwitchRequest{
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		SourceAMFUENGAPID: &ie.AMFUENGAPID{
			Value: 1014734679650,
		},
		UserLocationInformation: &ie.UserLocationInformation{
			Choice: &ie.UserLocationInformationNR{
				NRCGI: &ie.NRCGI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString{0x02, 0xf8, 0x39},
					},
					NRCellIdentity: &ie.NRCellIdentity{
						Value: aper.BitString{
							Bytes:     []byte{0x00, 0x01, 0x03, 0x00, 0x10},
							BitLength: 36,
						},
					},
					IEExtensions: nil,
				},
				TAI: &ie.TAI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString{0x02, 0xf8, 0x39},
					},
					TAC: &ie.TAC{
						Value: aper.OctetString{0x00, 0x00, 0x01},
					},
					IEExtensions: nil,
				},
				TimeStamp:    nil,
				IEExtensions: nil,
			},
		},
		UESecurityCapabilities: &ie.UESecurityCapabilities{
			NRencryptionAlgorithms: &ie.NRencryptionAlgorithms{
				Value: aper.BitString{
					Bytes:     []byte{0xff, 0xff},
					BitLength: 16,
				},
			},
			NRintegrityProtectionAlgorithms: &ie.NRintegrityProtectionAlgorithms{
				Value: aper.BitString{
					Bytes:     []byte{0xff, 0xff},
					BitLength: 16,
				},
			},
			EUTRAencryptionAlgorithms: &ie.EUTRAencryptionAlgorithms{
				Value: aper.BitString{
					Bytes:     []byte{0xff, 0xff},
					BitLength: 16,
				},
			},
			EUTRAintegrityProtectionAlgorithms: &ie.EUTRAintegrityProtectionAlgorithms{
				Value: aper.BitString{
					Bytes:     []byte{0xff, 0xff},
					BitLength: 16,
				},
			},
			IEExtensions: nil,
		},
		PDUSessionResourceToBeSwitchedDLList: &ie.PDUSessionResourceToBeSwitchedDLList{
			List: []ie.PDUSessionResourceToBeSwitchedDLItem{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 10,
					},

					PathSwitchRequestTransfer: &aper.OctetString{0x00, 0x1f, 0xac, 0x10, 0x1f, 0x33, 0x00, 0x00, 0x00, 0x02, 0x00, 0x02},
					IEExtensions:              nil,
				},
			},
		},
		PDUSessionResourceFailedToSetupListPSReq: nil,
		RRCResumeCause:                           nil,
		RedCapIndication:                         nil,
	}
}

func sampleRANConfigurationUpdate() ngapMessage.Message {
	return &ngapMessage.RANConfigurationUpdate{}
}

func sampleUEContextReleaseComplete() ngapMessage.Message {
	plmnIdentity_case1 := &ie.PLMNIdentity{Value: aper.OctetString([]byte{0x13, 0x30, 0x01})}
	_ = plmnIdentity_case1
	tac_case1 := &ie.TAC{Value: aper.OctetString([]byte{0x00, 0x00, 0x01})}
	_ = tac_case1
	nrCellIdentity_case1 := &ie.NRCellIdentity{
		Value: aper.BitString{
			Bytes:     []byte{0x00, 0x00, 0x02, 0xb6, 0x70},
			BitLength: 36,
		},
	}
	_ = nrCellIdentity_case1
	plmnIdentity_case2 := &ie.PLMNIdentity{Value: aper.OctetString([]byte{0x00, 0x00, 0x00})}
	_ = plmnIdentity_case2
	tac_case2 := &ie.TAC{Value: aper.OctetString([]byte{0x00, 0x00, 0x00})}
	_ = tac_case2
	nrCellIdentity_case2 := &ie.NRCellIdentity{
		Value: aper.BitString{
			Bytes:     []byte{0x00, 0x00, 0x00, 0x00, 0x10},
			BitLength: 36,
		},
	}
	_ = nrCellIdentity_case2
	nid_case2 := &ie.NID{
		Value: aper.BitString{
			Bytes:     []byte{0x99, 0x99, 0x99, 0x99, 0x99, 0x90},
			BitLength: 44,
		},
	}
	_ = nid_case2
	return &ngapMessage.UEContextReleaseComplete{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 885695317650,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		UserLocationInformation: &ie.UserLocationInformation{
			Choice: &ie.UserLocationInformationNR{
				NRCGI: &ie.NRCGI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString{0x02, 0xf8, 0x39},
					},
					NRCellIdentity: &ie.NRCellIdentity{
						Value: aper.BitString{
							Bytes:     []uint8{0x00, 0x00, 0x04, 0x00, 0x10},
							BitLength: 36,
						},
					},
				},
				TAI: &ie.TAI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: aper.OctetString{0x02, 0xf8, 0x39},
					},
					TAC: &ie.TAC{
						Value: aper.OctetString{0x00, 0x00, 0x01},
					},
				},
			},
		},
	}
}

func sampleUEContextReleaseRequest() ngapMessage.Message {
	return &ngapMessage.UEContextReleaseRequest{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 885695317650,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		PDUSessionResourceListCxtRelReq: &ie.PDUSessionResourceListCxtRelReq{
			List: []ie.PDUSessionResourceItemCxtRelReq{
				{
					PDUSessionID: &ie.PDUSessionID{
						Value: 10,
					},
				},
			},
		},
		Cause: &ie.Cause{
			Choice: &ie.CauseRadioNetwork{
				Value: aper.Enumerated(1),
			},
		},
	}
}

func sampleUERadioCapabilityInfoIndication() ngapMessage.Message {
	return &ngapMessage.UERadioCapabilityInfoIndication{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 1,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 3456106496,
		},
		UERadioCapability: &ie.UERadioCapability{
			Value: aper.OctetString([]byte{0x10, 0x14, 0x00, 0x00, 0x1f, 0xf8, 0x00, 0x00, 0x00, 0x00, 0xff, 0xc0}),
		},
	}
}

func sampleUplinkNASTransport() ngapMessage.Message {
	return &ngapMessage.UplinkNASTransport{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 240015147374,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		NASPDU: &ie.NASPDU{
			Value: []byte{
				0x7e, 0x00, 0x57, 0x2d, 0x10, 0xcc, 0xfa, 0xdc, 0xc0, 0x8d, 0xdb,
				0x56, 0x4e, 0xfd, 0x78, 0x04, 0xf9, 0xa2, 0x3b, 0xa9, 0x63,
			},
		},
		UserLocationInformation: &ie.UserLocationInformation{
			Choice: &ie.UserLocationInformationNR{
				NRCGI: &ie.NRCGI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: []byte{0x02, 0xf8, 0x39},
					},
					NRCellIdentity: &ie.NRCellIdentity{
						Value: aper.BitString{
							Bytes:     []byte{0x00, 0x00, 0x04, 0x00, 0x10},
							BitLength: 36,
						},
					},
					IEExtensions: nil,
				},
				TAI: &ie.TAI{
					PLMNIdentity: &ie.PLMNIdentity{
						Value: []byte{0x02, 0xf8, 0x39},
					},
					TAC: &ie.TAC{
						Value: []byte{0x00, 0x00, 0x01},
					},
					IEExtensions: nil,
				},
				TimeStamp: nil,
				IEExtensions: &ie.ProtocolExtensionContainerUserLocationInformationNRExtIEs{
					List: []ie.UserLocationInformationNRExtIEs{
						{
							Id: &ie.ProtocolExtensionID{
								Value: 263,
							},
							Criticality: &ie.Criticality{
								Value: 0,
							},
							PSCellInformation: nil,
							NID: &ie.NID{
								Value: aper.BitString{
									Bytes:     []byte{0x10, 0x00, 0x00, 0x00, 0x00, 0x10},
									BitLength: 44,
								},
							},
							NRNTNTAIInformation: nil,
						},
					},
				},
			},
		},
		WAGFIdentityInformation: nil,
		TNGFIdentityInformation: nil,
		TWIFIdentityInformation: nil,
	}
}

func sampleUplinkRANStatusTransfer() ngapMessage.Message {
	intPtr := func(i int64) *int64 {
		return &i
	}
	_ = intPtr
	return &ngapMessage.UplinkRANStatusTransfer{
		AMFUENGAPID: &ie.AMFUENGAPID{
			Value: 910057611806,
		},
		RANUENGAPID: &ie.RANUENGAPID{
			Value: 1,
		},
		RANStatusTransferTransparentContainer: &ie.RANStatusTransferTransparentContainer{
			DRBsSubjectToStatusTransferList: &ie.DRBsSubjectToStatusTransferList{
				List: []ie.DRBsSubjectToStatusTransferItem{
					{
						DRBID: &ie.DRBID{
							Value: 123,
						},
						DRBStatusUL: &ie.DRBStatusUL{
							Choice: &ie.DRBStatusUL12{
								ULCOUNTValue: &ie.COUNTValueForPDCPSN12{
									PDCPSN12:     intPtr(898),
									HFNPDCPSN12:  intPtr(345),
									IEExtensions: nil,
								},
								ReceiveStatusOfULPDCPSDUs: nil,
								IEExtension:               nil,
							},
						},
						DRBStatusDL: &ie.DRBStatusDL{
							Choice: &ie.DRBStatusDL12{
								DLCOUNTValue: &ie.COUNTValueForPDCPSN12{
									PDCPSN12:     intPtr(907),
									HFNPDCPSN12:  intPtr(987),
									IEExtensions: nil,
								},
								IEExtension: nil,
							},
						},
						IEExtension: nil,
					},
				},
			},
			IEExtensions: nil,
		},
	}
}
