package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		panic("usage: gen_ngap_samples <ngap-message-dir>")
	}
	wanted := map[string]bool{}
	for _, name := range strings.Fields(`NGSetupRequest NGReset NGResetAcknowledge InitialUEMessage ErrorIndication UEContextReleaseRequest UEContextReleaseComplete UEContextModificationResponse UplinkNASTransport InitialContextSetupResponse InitialContextSetupFailure PathSwitchRequest HandoverRequestAcknowledge HandoverFailure PDUSessionResourceReleaseResponse AMFConfigurationUpdateFailure UERadioCapabilityCheckRequest UERadioCapabilityCheckResponse HandoverCancel LocationReportingFailureIndication PDUSessionResourceSetupResponse PDUSessionResourceModifyResponse PDUSessionResourceNotify PDUSessionResourceModifyIndication UEContextModificationFailure RRCInactiveTransitionReport HandoverNotify UplinkRANStatusTransfer NASNonDeliveryIndication RANConfigurationUpdate AMFStatusIndication UplinkRANConfigurationTransfer UplinkUEAssociatedNRPPaTransport UplinkNonUEAssociatedNRPPaTransport LocationReport UETNLABindingReleaseRequest UERadioCapabilityInfoIndication AMFConfigurationUpdateAcknowledge AMFConfigurationUpdate HandoverRequired CellTrafficTrace NGSetupResponse PDUSessionResourceModifyConfirm PDUSessionResourceReleaseCommand OverloadStart OverloadStop`) {
		wanted[name] = true
	}
	fset := token.NewFileSet()
	type sample struct {
		prelude []string
		expr    string
	}
	found := map[string]sample{}
	files, err := filepath.Glob(filepath.Join(os.Args[1], "*_test.go"))
	if err != nil {
		panic(err)
	}
	for _, path := range files {
		file, parseErr := parser.ParseFile(fset, path, nil, 0)
		if parseErr != nil {
			panic(parseErr)
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil {
				continue
			}
			var prelude []string
			for _, stmt := range fn.Body.List {
				var matchedName, matchedExpr string
				ast.Inspect(stmt, func(node ast.Node) bool {
					unary, ok := node.(*ast.UnaryExpr)
					if !ok || unary.Op != token.AND {
						return true
					}
					literal, ok := unary.X.(*ast.CompositeLit)
					if !ok {
						return true
					}
					ident, ok := literal.Type.(*ast.Ident)
					if !ok || !wanted[ident.Name] || found[ident.Name].expr != "" {
						return true
					}
					var source strings.Builder
					if format.Node(&source, fset, unary) == nil {
						matchedName = ident.Name
						matchedExpr = strings.Replace(source.String(), "&"+ident.Name,
							"&ngapMessage."+ident.Name, 1)
					}
					return false
				})
				if matchedName != "" {
					found[matchedName] = sample{prelude: append([]string(nil), prelude...), expr: matchedExpr}
					break
				}
				if assign, ok := stmt.(*ast.AssignStmt); ok && assign.Tok == token.DEFINE {
					var source strings.Builder
					if format.Node(&source, fset, assign) == nil {
						prelude = append(prelude, source.String())
					}
				}
			}
		}
	}
	names := make([]string, 0, len(found))
	for name := range found {
		names = append(names, name)
	}
	sort.Strings(names)
	fmt.Println("// Code generated by .tools/gen_ngap_samples.go; DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package ngapTestpacket")
	fmt.Println()
	fmt.Println("import (")
	fmt.Println("\t\"github.com/free5gc/ngap/aper\"")
	fmt.Println("\t\"github.com/free5gc/ngap/ie\"")
	fmt.Println("\tngapMessage \"github.com/free5gc/ngap/message\"")
	fmt.Println(")")
	for _, name := range names {
		fmt.Printf("\nfunc sample%s() ngapMessage.Message {\n", name)
		for _, statement := range found[name].prelude {
			fmt.Printf("\t%s\n", statement)
			lhs, _, ok := strings.Cut(statement, ":=")
			if ok {
				for variable := range strings.SplitSeq(lhs, ",") {
					fmt.Printf("\t_ = %s\n", strings.TrimSpace(variable))
				}
			}
		}
		fmt.Printf("\treturn %s\n}\n", found[name].expr)
	}
	for name := range wanted {
		if found[name].expr == "" {
			fmt.Fprintf(os.Stderr, "missing %s\n", name)
		}
	}
}
